//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceService.Console.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Individual,954413127425426#A0LkikI1pjIEJCLi4TPBR4QPRTN6kTS5BXbOJnYM3kNDFnbWZEWzZGc98EMzdXOUlFUYh5Yuh4ZYlFduZ7c8pHcl3EbDFUaLNzcShGawImQ5d7MV34UrN4QFF5KGBnSQJTd6llI0IyUiwiN4EDM6QjM4kTM0IicfJye&Qf35VfiEEM9MkI0IyQiwiIxYFI4VmTuACblNGeFBicvZGI49WZtV7YvREIDdkI0IiTis7W0ICZyBlIsIyN4ITN4ADIwMDMxgTMwIjI0ICdyNkIsICbhVHZpZXak9WSiojIh94QiwiI6IDN5IDN7ITMzEDN4UTOioj")]
        public string DioDocsForExcelKey {
            get {
                return ((string)(this["DioDocsForExcelKey"]));
            }
        }
    }
}
